name: Print Text File

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main        

jobs:
    read_the_file:
        runs-on: ubunto-latest
        steps:
            - name: Git checkout korbo
              uses: actions/checkout@v2
            - name: read txt
              run: cat hello.txt